name: Versioning Automation with SemVer

on:
  workflow_call:

jobs:
  Workflow-versioning:
    runs-on: ubuntu-latest

    steps:
     - name: Workflow version
       id: versioning
       uses: AtarB2B/github-semantic-versioning-actions@latest
